/**
 * lib/recipes/confidence.ts — PRD 11 composite confidence scoring.
 *
 * Deterministic, rule-based (11.4: "not generated by LLM alone" — here there
 * is no LLM at all). Every input is returned as an inspectable string map so
 * the UI, ledger, and audits can show exactly why a label was assigned.
 */

import type { ActivationLevel, Confidence, MeasurementMode } from "../contracts";
import type { BaselineAvailability } from "./types";

/** PRD 11.1 inputs. All fields are required except productRepeatability (recipe 2 only). */
export interface ConfidenceInputs {
  /** All required sources within freshness threshold. */
  dataFresh: boolean;
  /** Final eligible audience size. */
  audienceSize: number;
  /** eligible-after-consent / considered ratio in [0,1]. */
  consentRatio: number;
  /** PRD 16.3 baseline availability for the estimate. */
  baseline: BaselineAvailability;
  /** Activation level the recipe recommends. */
  activationLevel: ActivationLevel;
  /** Measurement mode the plan resolved to (after 26A.1 downgrade). */
  measurementMode: MeasurementMode;
  /** Identity-join / field coverage in [0,1] (26B.12). */
  sourceCompleteness: number;
  /** All three v0 recipes ship at 1.0.0 — "new". */
  recipeMaturity: "new" | "established";
  /** Recipe 2 only: repeatability of the products driving the audience (26A.7). */
  productRepeatability?: "strong" | "partial" | "weak";
  /** 26A.5 — active-flow exclusion derived from proxy/unavailable data lowers confidence. */
  flowExclusionReliable?: boolean;
}

export interface ConfidenceScore {
  confidence: Confidence;
  /** PRD 11.4 — inspectable inputs, human-readable. */
  inputs: Record<string, string>;
}

/** Direct activation exists when the operator can create the object itself (PRD 11.2). */
function isDirectActivation(level: ActivationLevel): boolean {
  return (
    level === "klaviyo_flow_draft" ||
    level === "klaviyo_campaign_draft" ||
    level === "meta_audience_sync"
  );
}

/**
 * PRD 11.2 label rules, applied in order:
 *  - LOW when any hard low-signal is present (stale data, directional-only
 *    measurement, no baseline, tiny audience, weak product repeatability,
 *    unreliable flow exclusions).
 *  - HIGH only when all high-bar conditions hold (fresh, >500, clear consent,
 *    direct activation, merchant-historical baseline, holdout-verifiable,
 *    strong source completeness).
 *  - MEDIUM otherwise.
 */
export function scoreConfidence(s: ConfidenceInputs): ConfidenceScore {
  const lowReasons: string[] = [];
  if (!s.dataFresh) lowReasons.push("stale source data");
  if (s.measurementMode === "directional") lowReasons.push("directional-only measurement");
  if (s.baseline === "none") lowReasons.push("no baseline available");
  if (s.audienceSize < 100) lowReasons.push("audience under 100");
  if (s.productRepeatability === "weak") lowReasons.push("product repeatability unclear/weak");
  if (s.flowExclusionReliable === false)
    lowReasons.push("active-flow exclusions inferred from proxy or unavailable (26A.5)");
  if (s.recipeMaturity !== "new" && s.recipeMaturity !== "established")
    lowReasons.push("unknown recipe maturity");

  const highBar =
    s.dataFresh &&
    s.audienceSize > 500 &&
    s.consentRatio >= 0.5 &&
    isDirectActivation(s.activationLevel) &&
    s.baseline === "merchant_historical" &&
    s.measurementMode === "holdout" &&
    s.sourceCompleteness >= 0.8 &&
    (s.productRepeatability === undefined || s.productRepeatability === "strong");

  const confidence: Confidence =
    lowReasons.length > 0 ? "low" : highBar ? "high" : "medium";

  const inputs: Record<string, string> = {
    data_freshness: s.dataFresh ? "all required sources fresh" : "one or more sources stale",
    audience_size: `${s.audienceSize} eligible customers (${s.audienceSize > 500 ? ">500" : "<=500"})`,
    consent_eligibility: `${Math.round(s.consentRatio * 100)}% of considered customers consent-eligible`,
    baseline_availability:
      s.baseline === "merchant_historical"
        ? "merchant historical baseline"
        : s.baseline === "modeled"
          ? "conservative modeled baseline (assumption, editable)"
          : "no baseline",
    direct_activation: isDirectActivation(s.activationLevel)
      ? `direct activation available (${s.activationLevel})`
      : `activation fallback needed (${s.activationLevel})`,
    measurement_quality:
      s.measurementMode === "holdout"
        ? "holdout-verified measurement"
        : s.measurementMode === "before_after_no_control"
          ? "before/after, no control group"
          : "directional only",
    source_completeness: `${Math.round(s.sourceCompleteness * 100)}% identity-join coverage`,
    recipe_maturity: s.recipeMaturity === "new" ? "new v0 recipe (1.0.0)" : "established recipe",
  };
  if (s.productRepeatability !== undefined) {
    inputs.product_repeatability = `${s.productRepeatability} product repeatability`;
  }
  if (s.flowExclusionReliable !== undefined) {
    inputs.flow_exclusion_reliability = s.flowExclusionReliable
      ? "active-flow exclusions from flow membership"
      : "active-flow exclusions from proxy/unavailable data — contamination risk";
  }
  inputs.label_rule =
    lowReasons.length > 0
      ? `LOW because: ${lowReasons.join("; ")}`
      : highBar
        ? "HIGH: all high-bar conditions met (fresh, >500, consent clear, direct activation, merchant baseline, holdout-verifiable, strong completeness)"
        : "MEDIUM: no hard low-signals, but not all high-bar conditions met";

  return { confidence, inputs };
}
